# 1. TVTK入门

In [1]:
from tvtk.tools import tvtk_doc

tvtk_doc.main()

In [2]:
from tvtk.api import tvtk

s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
print(s)

vtkCubeSource (000002A2CD8B0370)
  Debug: Off
  Modified Time: 1257590
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (000002A2CDB47BF0)
        Event: 33
        EventName: ModifiedEvent
        Command: 000002A2CDFA2640
        Priority: 0
        Tag: 1
  Executive: 000002A2CD945140
  ErrorCode: No error
  Information: 000002A2CDD0F920
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  X Length: 1
  Y Length: 2
  Z Length: 3
  Center: (0, 0, 0)
  Output Points Precision: 0




### TVTK库帮助资源
#### http://vtk.org/doc/nightly/html/annotated.html

### CubeSource对象的属性

|属性|说明|
|:-:|:-:|
|s.x_length|长方体对象在X轴方向的长度|
|s.y_length|长方体对象在Y轴方向的长度|
|s.z_length|长方体对象在Z轴方向的长度|
|s.center|长方体对象所在坐标系的原点|
|s.output_points_precision|长方体对象的精度|
|……|……|

In [8]:
s.x_length
s.y_length
s.z_length

1.0

2.0

3.0

In [3]:
s.center

array([ 0.,  0.,  0.])

In [4]:
s.output_points_precision

0

### CubeSource对象的方法

|方法|说明|
|:-:|:-:|
|set/get_x_length()|设置/获取长方体对象在X轴方向的长度|
|set/get_y_length()|设置/获取长方体对象在Y轴方向的长度|
|set/get_z_length()|设置/获取长方体对象在Z轴方向的长度|
|set/get_center()|设置/获取长方体对象所在坐标系的原点|
|set/get_bounds()|设置/获取长方体对象的包围盒|
|……|……|

### TVTK库的基本三维对象

|三维对象|说明|
|:-:|:-:|
|CubeSource|立方体三位对象数据源|
|ConeSource|圆锥三维对象数据源|
|CylinderSource|圆柱三维对象数据源|
|ArcSource|圆弧三维对象数据源|
|ArrowSource|箭头三维对象数据源|
|……|……|

In [11]:
from tvtk.api import tvtk

s = tvtk.ConeSource(height=3.0, radius=1.0, resolution=36)

s.height
s.radius
s.resolution
s.center

3.0

1.0

36

array([ 0.,  0.,  0.])

In [12]:
print(s)

vtkConeSource (000001E1F42820C0)
  Debug: Off
  Modified Time: 1257627
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (000001E1F4B89DE0)
        Event: 33
        EventName: ModifiedEvent
        Command: 000001E1FE00B630
        Priority: 0
        Tag: 1
  Executive: 000001E1F4C851D0
  ErrorCode: No error
  Information: 000001E1FE1034D0
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  Resolution: 36
  Height: 3
  Radius: 1
  Capping: On
  Center: (0, 0, 0)
  Direction: (1, 0, 0)
  Output Points Precision: 0




### 显示一个长方体

In [4]:
from tvtk.api import tvtk

# 创建一个长方体数据源，并且同时设置其长宽高
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
# 使用PolyDataMapper将数据转换为图形数据
m = tvtk.PolyDataMapper(input_connection=s.output_port)

# 创建一个Actor
a = tvtk.Actor(mapper=m)
# 创建一个Renderer，将Actor添加进去
r = tvtk.Renderer(background=(0,0,0))
r.add_actor(a)
# 创建一个RenderWindow(窗口)，将Renderer添加进去
w = tvtk.RenderWindow(size=(300,300))
w.add_renderer(r)
# 创建一个RenderWindowInteractor(窗口的交互工具)
i = tvtk.RenderWindowInteractor(render_window=w)
# 开启交互
i.initialize()
i.start()

![cube](./Image/cube.png)

# 2. TVTK管线与数据加载

## 2.1 管线技术(Pipeline, 流水线)
**可视化管线(Visualization Pipeline):** 将原始数据加工成图形数据的过程  
**图形管线(Graphics Pipeline):** 图形数据加工为我们所看到图像的过程  

**数据 <——> 数据预处理 <——> 数据映射 <——> 绘制(Rendering) <——> 显示(Displaying)**  
**|-----------可视化管线-----------|------------------------------------图形管线------------------------------------|**

### 可视化管线
|TVTK对象|说明|
|:-:|:-:|
|CubeSource|通过程序内部计算输出一组描述长方体的数据(PolyData)|
|PolyDataMapper|PolyData通过该映射器将数据映射为图片数据(mapper)|

In [14]:
s.output_port

In [15]:
m.input_connection

### 图形管线
|TVTK对象|说明|
|:-:|:-:|
|Actor|场景中的一个实体。它包括一个图形数据(mapper)，<br>具有描述该实体的位置、方向、大小的属性|
|Renderer|渲染的场景。它包括多个需要渲染的Actor|
|RenderWindow|渲染用的图形窗口。它包括一个或者多个Render|
|RenderWindowInteractor|给图形窗口提供一些用户交互功能，<br>例如平移、旋转、放缩|

## 2.2 用ivtk工具观察管线

**from tvtk.tools import ivtk**

In [18]:
from tvtk.api import tvtk
from tvtk.tools import ivtk
from pyface.api import GUI

s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
m = tvtk.PolyDataMapper(input_connection=s.output_port)
a = tvtk.Actor(mapper=m)

# 创建一个带Crust的窗口
gui = GUI()
win = ivtk.IVTKWithCrustAndBrowser()
win.open()
win.scene.add_actor(a)

# 修正窗口界面错误
dialog = win.control.centralWidget().widget(0).widget(0)
from pyface.qt import QtCore
dialog.setWindowFlags(QtCore.Qt.WindowFlags(0x00000000))
dialog.show()

# 开始界面消息循环
gui.start_event_loop()

## 2.3 数据集(Dataset)
- 点(Point)和数据(Data)
- 点之间: 连接 vs 非连接
- 多个相关点组成单元(Cell)
- 点的连接: 显示 vs 隐式
- 数据: 标量(Scalar) vs 矢量(Vector)


- ImageData
- RectilinearGrid
- StructedGrid
- PolyData
- UnstructuredGrid

### ImageData 数据集
#### ImageData表示二维或三维图像的数据结构
|参数|说明|
|:-:|:-:|
|spacing|三位网格数据的起点坐标|
|origin|三维网格数据在X、Y、Z轴上的间距|
|dimensions|在X、Y、Z轴上的网格数|

In [19]:
from tvtk.api import tvtk

img = tvtk.ImageData(spacing=(1,1,1), origin=(1,2,3), dimensions=(3,4,5))
img.get_point(0)

(1.0, 2.0, 3.0)

In [20]:
for n in range(6):
    print("%.1f, %.1f, %.1f" % img.get_point(n))

1.0, 2.0, 3.0
2.0, 2.0, 3.0
3.0, 2.0, 3.0
1.0, 3.0, 3.0
2.0, 3.0, 3.0
3.0, 3.0, 3.0


### RectilinearGrid 数据集
#### RectilinearGrid: 间距不均匀的网络，所有点都在正交的网格上

In [22]:
from tvtk.api import tvtk
import numpy as np

x = np.array([0,3,9,15])
y = np.array([0,1,5])
z = np.array([0,2,3])

r = tvtk.RectilinearGrid()
r.x_coordinates = x
r.y_coordinates = y
r.z_coordinates = z
r.dimensions = len(x), len(y), len(z)

In [24]:
for i in range(6):
    print(r.get_point(i))

(0.0, 0.0, 0.0)
(3.0, 0.0, 0.0)
(9.0, 0.0, 0.0)
(15.0, 0.0, 0.0)
(0.0, 1.0, 0.0)
(3.0, 1.0, 0.0)


### StructuredGrid 数据集
#### StructuredGrid: 创建任意形状的网格，需要指定点的坐标

### PolyData 数据集
#### PolyData: 由一系列的点、点之间的联系以及由点构成的多边形组成

## 2.4 TVTK数据加载

### 读入STL文件
**s = tvtk.STLReader(file_name = "filename.stl")**

In [2]:
from tvtk.api import tvtk
from tvtkfunc import ivtk_scene, event_loop

s = tvtk.STLReader(file_name = "./Data/python.stl")
m = tvtk.PolyDataMapper(input_connection = s.output_port)
a = tvtk.Actor(mapper = m)

win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

![python_stl](./Image/python_stl.png)

### MultiBlock数据读取

In [8]:
from tvtk.api import tvtk

# 读入数据
def read_data():
    plot3d = tvtk.MultiBlockPLOT3DReader(
            xyz_file_name = "./Data/combxyz.bin", # 网格文件
            q_file_name = "./Data/combq.bin", # 空气动力学结果文件
            scalar_function_number = 100, # 设置标量数据数量
            vector_function_number = 200 # 设置矢量数据数量
        )
    plot3d.update()
    return plot3d

plot3d = read_data() # 让plot3D计算其输出数据
grid = plot3d.output.get_block(0) # 获取读入的数据集对象

In [9]:
print(type(plot3d.output))

<class 'tvtk.tvtk_classes.multi_block_data_set.MultiBlockDataSet'>


In [10]:
print(type(plot3d.output.get_block(0)))

<class 'tvtk.tvtk_classes.structured_grid.StructuredGrid'>


In [11]:
print(grid.dimensions)

[57 33 25]


In [12]:
print(grid.points.to_array())

[[  2.66700006  -3.77476001  23.83292007]
 [  2.94346499  -3.74825287  23.66555977]
 [  3.21985817  -3.72175312  23.49823952]
 ..., 
 [ 15.84669018   5.66214085  35.7493782 ]
 [ 16.17829895   5.66214085  35.7493782 ]
 [ 16.51000023   5.66214085  35.7493782 ]]


In [14]:
print(grid.point_data.number_of_arrays)

4


In [16]:
print(grid.point_data.scalars.name)

Density


In [18]:
print(grid.point_data.vectors.name)

Velocity


# 3 TVTK库可视化实例

## 实例1: 标量数据可视化

#### tvtk.ContourFilter() 等值面过滤器
|方法|说明|
|:-:|:-:|
|generate_values()|设定n条等值线的值<br>一般用于重新绘制等值线|
|set_value()|设定一条等值线的值<br>一般用于覆盖某条等值线或者新增加一条等值线|

In [22]:
from tvtk.api import tvtk
from tvtkfunc import ivtk_scene, event_loop

# 读入数据
def read_data():
    plot3d = tvtk.MultiBlockPLOT3DReader(
            xyz_file_name = "./Data/combxyz.bin", # 网格文件
            q_file_name = "./Data/combq.bin", # 空气动力学结果文件
            scalar_function_number = 100, # 设置标量数据数量
            vector_function_number = 200 # 设置矢量数据数量
        )
    plot3d.update()
    return plot3d

plot3d = read_data() # 让plot3D计算其输出数据
grid = plot3d.output.get_block(0) # 获取读入的数据集对象

con = tvtk.ContourFilter() # 创建等值面对象
con.set_input_data(grid)
con.generate_values(10, grid.point_data.scalars.range) # 制定轮廓数和数据范围

# 设定映射器的变量范围属性
m = tvtk.PolyDataMapper(scalar_range = grid.point_data.scalars.range,
                        input_connection = con.output_port)
a = tvtk.Actor(mapper = m)
a.property.opacity = 0.5 # 设定透明度为0.5

# 窗口绘制
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

![](./Image/EX1.png)

## 实例2: 矢量数据可视化
#### tvtk.Glyph3D() 符号化技术
#### tvtk.MaskPoints() 降采样

In [23]:
from tvtk.api import tvtk
from tvtkfunc import ivtk_scene, event_loop

# 读入Plot3D数据
plot3d = tvtk.MultiBlockPLOT3DReader(
    xyz_file_name = "./Data/combxyz.bin", # 网格文件
    q_file_name = "./Data/combq.bin", # 空气动力学结果文件
    scalar_function_number = 100, # 设置标量数据数量
    vector_function_number = 200 # 设置矢量数据数量
)
plot3d.update() # 让plot3D计算其输出数据
grid = plot3d.output.get_block(0) # 获取读入的数据集对象

# 对数据集中的数据进行随机选取，每50个点选择一个点
mask = tvtk.MaskPoints(random_mode=True, on_ratio=50)
mask.set_input_data(grid)

# 创建表示箭头的PolyData数据集
glyph_source = tvtk.ArrowSource()

# 在Mask采样后的PolyData数据集每个点上放置一个箭头
glyph = tvtk.Glyph3D(input_connection=mask.output_port, scale_factor=4)
glyph.set_source_connection(glyph_source.output_port)
m = tvtk.PolyDataMapper(scalar_range=grid.point_data.scalars.range,
                        input_connection=glyph.output_port)
a = tvtk.Actor(mapper=m)

# 窗口绘制
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

![](./Image/EX2_1.png)

In [24]:
print(grid.number_of_points)

47025


In [25]:
mask.update()
print(mask.output.number_of_points)

930


In [28]:
# 创建表示圆锥的PolyData数据集
glyph_source = tvtk.ConeSource()

# 在Mask采样后的PolyData数据集每个点上放置一个箭头
glyph = tvtk.Glyph3D(input_connection=mask.output_port, scale_factor=2)
glyph.set_source_connection(glyph_source.output_port)
m = tvtk.PolyDataMapper(scalar_range=grid.point_data.scalars.range,
                        input_connection=glyph.output_port)
a = tvtk.Actor(mapper=m)

# 窗口绘制
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

![](./Image/EX2_2.png)

## 实例3: 空间轮廓线可视化
#### tvtk.StructuredGridOutlineFilter() 计算PolyData对象的外边框

In [29]:
from tvtk.api import tvtk
from tvtkfunc import ivtk_scene, event_loop
from tvtk.common import configure_input

# 读入Plot3D数据
plot3d = tvtk.MultiBlockPLOT3DReader(
    xyz_file_name = "./Data/combxyz.bin", # 网格文件
    q_file_name = "./Data/combq.bin", # 空气动力学结果文件
    scalar_function_number = 100, # 设置标量数据数量
    vector_function_number = 200 # 设置矢量数据数量
)
plot3d.update() # 让plot3D计算其输出数据
grid = plot3d.output.get_block(0) # 获取读入的数据集对象

# 计算表示外边框的PolyData对象
outline = tvtk.StructuredGridOutlineFilter()
# 调用tvtk.common.configure_input()
configure_input(outline, grid)

m = tvtk.PolyDataMapper(input_connection=outline.output_port)
a = tvtk.Actor(mapper=m)
a.property.color = 0.3, 0.3, 0.3

# 窗口绘制
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

![](./Image/EX3.png)