# PyToch Base

In [2]:
import torch

## Tensor

In [3]:
torch.Tensor(5, 4)


-3.0626e-34  4.5908e-41 -3.0626e-34  4.5908e-41
 1.4574e-43  6.4460e-44  1.1771e-43  1.4153e-43
 1.5414e-43  1.6115e-43  1.5554e-43  1.5975e-43
 5.6052e-44  7.4269e-44  6.1657e-44  4.4842e-44
 7.2868e-44  5.7453e-44  4.4721e+21  1.6647e-41
[torch.FloatTensor of size 5x4]

In [4]:
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [5]:
b = a.numpy()
print(b)

[[ 0.29404217  0.88885844  0.82094043  0.86786741]
 [ 0.77458388  0.51390553  0.29790932  0.92242551]
 [ 0.99573749  0.49975112  0.80724651  0.82399648]
 [ 0.91063142  0.69013143  0.19753452  0.23817185]
 [ 0.86245584  0.08150768  0.60304117  0.28878206]]


## Variable

In [19]:
from torch.autograd import Variable
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2*x + y + 4
print(z)

Variable containing:
 15
[torch.FloatTensor of size 1]



In [20]:
# 对x和y分别求导
z.backward()

In [21]:
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: 
 2
[torch.FloatTensor of size 1]

dz/dy: 
 1
[torch.FloatTensor of size 1]



## Neural Network 

In [24]:
import torch.nn as nn
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        
    def forward(self, x):
        # 定义前向传播
        out = self.conv1(x)
        return out