# 1. Numpy

## 1.1 从列表或元组转换

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndim=0)

In [4]:
import numpy as np

np.array([[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [5]:
np.array([(1,2), (3,4), (5,6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

## 1.2 arange 方法创建

numpy.arange(start, stop, step, dtype=None)

In [7]:
np.arange(3, 7, 0.5, dtype=float)

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5])

## 1.3 linspace 方法创建

numpy.linspace(start, stop, step, num=50, endpoint=True, retstep=False, dtype=None)

In [8]:
np.linspace(0, 10, 10, endpoint=True)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [9]:
np.linspace(0, 10, 10, endpoint=False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [10]:
np.linspace(0, 10, 10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

## 1.4 ones 方法创建

numpy.ones(shape, dtype=None, order='C')

In [11]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## 1.5 zeros 方法创建

numpy.zeros(shape, dtpye=None, order='C')

In [12]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## 1.6 eye 方法创建

In [14]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.eye(5, 4, 1)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.eye(4, 6, -1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.]])

## 1.7 从已知数据创建

np.fromfunction(lambda a, b: a+b, (5,4))

# 2. ndarray 数组属性

In [16]:
a = np.array([[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]])
a

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

## 2.1 ndarray.T

In [17]:
a.T

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

## 2.2 ndarray.dtype

In [18]:
a.dtype

dtype('int32')

## 2.3 ndarray.imag

In [19]:
a.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

## 2.4 ndarray.real

In [20]:
a.real

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

## 2.5 ndarray.size

In [21]:
a.size

27

## 2.6 ndarray.itemsize

In [22]:
a.itemsize

4

## 2.7 ndaray.nbytes

In [24]:
a.nbytes

108

## 2.8 ndarray.ndim

In [23]:
a.ndim

3

## 2.9 ndarray.shape

In [25]:
a.shape

(3, 3, 3)

## 2.10 ndarray.strides

In [26]:
a.strides

(36, 12, 4)