In [6]:
import tensorflow as tf
from numpy.random import RandomState

# 定义训练数据batch大小
batch_size = 8

# 定义神经网络的参数
w1 = tf.Variable(tf.random_normal([2,3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3,1], stddev=1, seed=1))

x = tf.placeholder(tf.float32, shape=(None,2), name='x-input')
y_ = tf.placeholder(tf.float32, shape=(None,1), name='y-input')

# 定义神经网络前向传播过程
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

#定义损失函数和反向传播的算法
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

# 通过随机数生成一个模拟数据集
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)

# 定义 x1+x2 < 1 的样例为正样本
Y = [[int(x1+x1<1)] for (x1,x2) in X]

# 创建一个会话来运行Tensorflow程序
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    # 初始化变量
    sess.run(init_op)
    print("Initail w1:\n", sess.run(w1))
    print("Initail w2:\n", sess.run(w2))
    
    # 设定训练的轮数
    STEPS = 5000
    for i in range(STEPS):
        # 每次选 batch_size 个样本进行训练
        start = (i*batch_size) % dataset_size
        end = min(start+batch_size, dataset_size)
        
        # 通过选取的样本训练神经网络并更新参数
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i%500 == 0:
            # 每隔一段时间计算所有数据上的交叉熵并输出
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training steps, cross_entropy on all data is %g" % (i, total_cross_entropy))
        
    print("After training w1:\n ", sess.run(w1))
    print("After training w2:\n", sess.run(w2))

Initail w1:
 [[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
Initail w2:
 [[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
After 0 training steps, cross_entropy on all data is 0.0674925
After 500 training steps, cross_entropy on all data is 0.0271219
After 1000 training steps, cross_entropy on all data is 0.0163385
After 1500 training steps, cross_entropy on all data is 0.0115551
After 2000 training steps, cross_entropy on all data is 0.00907547
After 2500 training steps, cross_entropy on all data is 0.00773293
After 3000 training steps, cross_entropy on all data is 0.00714436
After 3500 training steps, cross_entropy on all data is 0.00648791
After 4000 training steps, cross_entropy on all data is 0.00578471
After 4500 training steps, cross_entropy on all data is 0.00505237
After training w1:
  [[-1.96182752  2.58235407  1.68203771]
 [-3.46817183  1.06982315  2.11788988]]
After training w2:
 [[-1.82471502]
 [ 2.68546653]
 [ 1.41819501]]
